---
AWSTemplateFormatVersion: 2010-09-09

# ------------------------------------------------------------------------------------------------------------------------------------ #
# -----------------------------------------------------------    METADATA    --------------------------------------------------------- #
# ------------------------------------------------------------------------------------------------------------------------------------ #

Metadata:

# ------------------------------------------------------------------------------------------------------------------------------------ #
# ---------------------------------------------------------    PARAMETERS    --------------------------------------------------------- #
# ------------------------------------------------------------------------------------------------------------------------------------ #

Parameters:

# ------------------------------------------------------------------------------------------------------------------------------------ #
# ------------------------------------------------------------    RULES    ----------------------------------------------------------- #
# ------------------------------------------------------------------------------------------------------------------------------------ #

Rules:

# ------------------------------------------------------------------------------------------------------------------------------------ #
# -----------------------------------------------------------    MAPPINGS    --------------------------------------------------------- #
# ------------------------------------------------------------------------------------------------------------------------------------ #

Mappings:

# ------------------------------------------------------------------------------------------------------------------------------------ #
# ---------------------------------------------------------    CONDITIONS    --------------------------------------------------------- #
# ------------------------------------------------------------------------------------------------------------------------------------ #

Conditions:

# ------------------------------------------------------------------------------------------------------------------------------------ #
# ----------------------------------------------------------    TRANSFORM    --------------------------------------------------------- #
# ------------------------------------------------------------------------------------------------------------------------------------ #

Transforms:

# ------------------------------------------------------------------------------------------------------------------------------------ #
# ---------------------------------------------------------    RESOURCES    ---------------------------------------------------------- #
# ------------------------------------------------------------------------------------------------------------------------------------ #

Resources:

# ~~~~~~~~~~-------------------------------------------------    SUBNETS    ---------------------------------------------------------- #

# ~~~~~~~~~~-------------------------------------------    NETWORKING HARDWARE    ---------------------------------------------------- #

# ~~~~~~~~~~----------------------------------------    ROUTING TABLE AND ROUTES    -------------------------------------------------- #

# ~~~~~~~~~~---------------------------------------------    SECURITY GROUPS    ------------------------------------------------------ #


# ------------------------------------------------------------------------------------------------------------------------------------ #
# -----------------------------------------------------------    OUTPUTS    ---------------------------------------------------------- #
# ------------------------------------------------------------------------------------------------------------------------------------ #

Outputs: